# Generated by Django 2.2.6 on 2019-10-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='video_path',
        ),
        migrations.RemoveField(
            model_name='video',
            name='convert_date',
        ),
    ]
